# Find out more about tasks: http://docs.devo.ps/manual/tasks

id: build-meteor
name: Build Meteor app
type: task

vars:
  app_src: meteor_app_src

targets:
  - meteor
  
# Uncomment the following to add a deploy webhook; you may want to obfuscate the URL as this is public
triggers:
#  webhooks:
#    - path: deploy
  events:
    - node.meteor.create.success

steps:
  # Fetch/update the code from the git repo
  - run: devops git update
    options:
      repo: "{{ git_url }}"
      dest: /tmp/{{ app_src }}

  # Let's prepare the build destination
  - run: >
      sudo mkdir -p /opt/{{ app_name }} && 
      sudo chown -R devops. /opt/{{ app_name }}

  # Let's build the meteor app and deploy to its final location
  - run: >
      cd /tmp/{{ app_src }} && 
      meteor build /opt/{{ app_name }} --directory &&
      cd /opt/{{ app_name }}/bundle/programs/server &&
      npm install
  
  # Prepare the app
  - run: devops nodejs app add
    options: 
      name: "{{ app_name }}"
      root: /opt/{{ app_name }}/bundle
      script: main.js
      node_env: prod
      user: devops
      extra_env: >
        PORT=3000
        MONGO_URL=mongodb://meteor:{{ nodes.meteor.configuration.mongodb.users.meteor.password }}@localhost:27017/{{ database_name }}
        ROOT_URL=http://{{ domain }}
