# Find out more about tasks: http://docs.devo.ps/manual/tasks

id: build-meteor
name: Build Meteor app
type: task

vars:
  app_src: /tmp/meteor_app_src

targets:
  - meteor

steps:
  # Fetch/update the code from the git repo
  - run: devops git update
    options:
      repo: "{{ git_url }}"
      dest: "{{ app_src }}"

  # Let's build the bundle out of the meteor app
  - run: cd {{ app_src }} && meteor build bundle_app.tgz

  # Let's prepare the build destination
  - run: >
      sudo mkdir -p /opt/{{ app_name }} && 
      sudo chown -R devops. /opt/{{ app_name }}
  
  # Let's deploy the build
  - run: >
      tar xzf {{ app_src }}/bundle_app.tgz -C /opt/{{ app_name }} &&
      cd /opt/{{ app_name }}/bundle/programs/server &&
      npm install
  
  # Prepare the app
  - run: devops nodejs app add
    options: 
      name: "{{ app_name }}"
      root: /opt/{{ app_name }}/bundle
      script: main.js
      node_env: prod
      user: devops
      extra_env: >
        "PORT=3000
        MONGO_URL=mongodb://meteor:{{ nodes.meteor.configuration.mongodb.users.meteor.password }}@localhost:27017/{{ database_name }}"
